---
title: Back to Work
author: Lara Srinath
date: '2020-07-09'
slug: back-to-work
categories:
tags:
  - life
  - work
subtitle: ''
summary: 'Going back to work after a long time'
authors: []
lastmod: '2020-07-09T17:34:22+08:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: yes
projects: []
---

**AS** the world entered into lockdown to fight the pandemic, IT corporations all over the world moved on to embrace a new working situation. Telecommute or Work from home. It has been more than 100 days since I made myself physically present in client meetings. The long night (yes, a reference to GOT) came to end 3 weeks ago in Malaysia and normality has resumed.

The Malaysian Government had done a spectacular job of controlling virus (visit my **[CoVID19 Tracker](https://larasrinath.shinyapps.io/covid19/)**), yet I continued to work from home as a precaution to the wide spread pandemic. While it has been fun working from home, I did miss face to face meetings and the friendly chatter with my clients and colleagues.

As all things should come to end, my work from home has come to an end. I have to be present in office coming Monday (13th Jul, 2020). 

Looking back at the things that kept me entertained during the lockdown:

1. **Stargazing** (tough being in a well-lit city like Kuala Lumpur), but made use what is available. The Crux and Centaurus constellation have always been bright from my home. You can use them to find South. There is a new comet C/2020 F3 NEOWISE, rising East, which has so far evaded from my sight. 
2. **The Big bang Theory** (on repeat)
3. **Harry Potter** (books & movies)
4. **F.R.I.E.N.D.S**
5. **Twitter**
6. **DARK** A show that completely blew my mind


I'll be wearing a mask, to protect myself as well as others and will wash my hands regularly.




